language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t night91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true night91/docker-react npm run test
