language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t night91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true night91/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-809138976660"
  bucket_path: "Docker React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
